In [ ]:
!pip uninstall -y tensorboard
!pip uninstall -y tensorflow
!pip uninstall -y autoai-libs

!pip install -U geocoder
!pip install -U geopy
!pip install -U googlemaps
!pip install -U folium
!pip install -U numpy
!pip install -U pandas

import pandas as pd
import numpy as np

from pandas import json_normalize  # tranform JSON file into a pandas dataframe

import googlemaps
from datetime import datetime
import requests
import geopy

geopy.geocoders.options.default_user_agent = "my-application"

import json
import time
import folium
import ast

print('Ready')

In [ ]:
# @hidden_cell
EMAIL='razinkov@hotmail.com'
PASSWORD='nMNbKWe2uf4YHQZ'

In [ ]:
!wget --cookies=on --save-cookies cookies.txt --keep-session-cookies --post-data 'user=EMAIL&password=PASSWORD' 'https://www.ctt.pt/fecas/login?service=https%3A%2F%2Fwww.ctt.pt%2Ffemgu%2Fj_spring_cas_security_check.jspx'
!wget --cookies=on --load-cookies cookies.txt --keep-session-cookies 'https://www.ctt.pt/feapl_2/app/restricted/postalCodeSearch/postalCodeDownloadFiles!downloadPostalCodeFile.jspx' -O PostCodeFull.Pt.zip

In [ ]:
# @hidden_cell
# The following code contains the credentials for a file in your IBM Cloud Object Storage.
# You might want to remove those credentials before you share your notebook.
credentials = {
    'IAM_SERVICE_ID': 'iam-ServiceId-c718bc9c-6715-41c4-a090-ef49d30cf02e',
    'IBM_API_KEY_ID': 'nEAwnadbTDR7sZjg2dsuEPEqMP3WU1UFgh7WLkkMZppS',
    'ENDPOINT': 'https://s3.eu-geo.objectstorage.service.networklayer.com',
    'IBM_AUTH_ENDPOINT': 'https://iam.eu-gb.bluemix.net/oidc/token',
    'BUCKET': 'capstoneprojectthebattleofneighbo-donotdelete-pr-rpev4qjyoaz4ga'
}

In [ ]:
from ibm_botocore.client import Config
import ibm_boto3
def download_file_cos(credentials,local_file_name,key):  
    cos = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials['IBM_API_KEY_ID'],
    ibm_service_instance_id=credentials['IAM_SERVICE_ID'],
    ibm_auth_endpoint=credentials['IBM_AUTH_ENDPOINT'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials['ENDPOINT'])
    try:
        res=cos.download_file(Bucket=credentials['BUCKET'],Key=key,Filename=local_file_name)
    except Exception as e:
        print(Exception, e)
    else:
        print('File Downloaded')

In [ ]:
def upload_file_cos(credentials,local_file_name,key):  
    cos = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=credentials['IBM_API_KEY_ID'],
    ibm_service_instance_id=credentials['IAM_SERVICE_ID'],
    ibm_auth_endpoint=credentials['IBM_AUTH_ENDPOINT'],
    config=Config(signature_version='oauth'),
    endpoint_url=credentials['ENDPOINT'])
    try:
        res=cos.upload_file(Filename=local_file_name, Bucket=credentials['BUCKET'],Key=key)
    except Exception as e:
        print(Exception, e)
    else:
        print(' File Uploaded')

In [25]:
download_file_cos(credentials,'concelhos.txt','concelhos.txt')
download_file_cos(credentials,'distritos.txt','distritos.txt')
download_file_cos(credentials,'todos_cp.txt','todos_cp.txt')
download_file_cos(credentials,'location_geometry.csv','location_geometry.csv')
download_file_cos(credentials,'hotels_all.csv','hotels_all.csv')
download_file_cos(credentials,'hotels_Resort.csv','hotels_Resort.csv')
print('Done')

File Downloaded
File Downloaded
File Downloaded
File Downloaded
File Downloaded
File Downloaded
Done

In [ ]:
!ls -la

In [ ]:
df_DD=pd.read_csv('distritos.txt',sep=';',encoding='iso8859_15')
df_DD.head()

In [ ]:
df_CC=pd.read_csv('concelhos.txt',sep=';',encoding='iso8859_15')
df_CC=df_CC[df_CC['DD']==8]
df_CC.head()

In [ ]:
df_PostalCode=pd.read_csv('todos_cp.txt',sep=';',encoding='iso8859_15')
df_PostalCode.shape

In [ ]:
df_PostalCode=df_PostalCode[['DD','CC','LLLL','LOCALIDADE','CP4','CP3','CPALF']]
df_PostalCode.head()

In [ ]:
new_df=pd.DataFrame(df_PostalCode[df_PostalCode['DD']==8].groupby(['CPALF'])['CP4'].count())
new_df=new_df.reset_index()[['CPALF']]
new_df.head()

In [ ]:
new_df

In [ ]:
# @hidden_cell
GOOGLE_MAPS_API_KEY='AIzaSyAHTKqjGZeqgTu8xY6jGaSFbNzy_qS6EwE'

In [ ]:
all_locations=pd.DataFrame()
for ind in new_df.index:
    address='{}, Algarve, Portugal'.format(new_df['CPALF'][ind])
    try:
        gmaps = googlemaps.Client(key=GOOGLE_MAPS_API_KEY,timeout=2)
        location = gmaps.geocode(address)
    except geopy.exc.GeocoderUnavailable:
        print('GeocoderUnavailable')
        print(name)
    except urllib.error.URLError:
        print('URLError')
        print(name)
    except OSError:
        print('OSError')
        print(name)


    if all_locations.empty:
        all_locations=pd.DataFrame(json_normalize(location))
    else:
        all_locations=all_locations.append(json_normalize(location),sort=False)

print(all_locations.shape)

In [ ]:
all_locations=all_locations.reset_index()
location_geometry=all_locations[['geometry.location.lat','geometry.location.lng']].reset_index()
location_geometry.to_csv('location_geometry.csv',index=False)
upload_file_cos(credentials,'location_geometry.csv','location_geometry.csv')

In [ ]:
all_locations.head()

In [ ]:
all_locations=all_locations.reset_index()

In [ ]:
location_geometry.head()

In [ ]:
for ind in all_locations.index:
    azaz=pd.DataFrame(all_locations['address_components'][ind]).reset_index()
    print(azaz['short_name'][0])

In [ ]:
location_geometry=pd.read_csv('location_geometry.csv',sep=',',encoding='utf_8').reset_index()
location_geometry.head()

In [ ]:
location_geometry_sorted=location_geometry.sort_values(by=['geometry.location.lat', 'geometry.location.lng'],ignore_index=True).reset_index()[['geometry.location.lat','geometry.location.lng']]
location_geometry_sorted.head()

In [ ]:
# @hidden_cell
CLIENT_ID='SMSYPRW3UME43CU2SOU5IJT0P52JY0HZ4RJP0VQM1H4A1BB1'
CLIENT_SECRET='TTWDTJNW1K24SDZJS4A5LZKBHOKZ2LDJOOITQKBVPLRFNKPN'
VERSION='20200425'

In [ ]:
#category='4bf58dd8d48988d12f951735' # Resort
category='4bf58dd8d48988d1fa931735' # Hotel

all_hotels=pd.DataFrame()
for ind in location_geometry_sorted.index:

    latitude = location_geometry_sorted['geometry.location.lat'][ind]
    longitude = location_geometry_sorted['geometry.location.lng'][ind]

    url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}&intent=browse&categoryId={}'.format(
        CLIENT_ID, 
        CLIENT_SECRET,
        VERSION,
        latitude,
        longitude,
        9999,
        50,
        category)
    results = json_normalize(requests.get(url).json())
    try:
        if not results.empty:
            response_venues=results['response.venues'][0]
            if response_venues:
                if all_hotels.empty:
                    all_hotels=pd.DataFrame(response_venues)
                else:
                    all_hotels=all_hotels.append(response_venues,sort=False)
    except KeyError:
        print('Error')

print(len(all_hotels))

In [ ]:
all_hotels.head()

In [ ]:
all_hotels=all_hotels.reset_index()[['id','name','location']]
all_hotels.head()

In [ ]:
all_hotels_location=pd.DataFrame(all_hotels[['location']]).reset_index()
#all_hotels_location.head()
#all_hotels_location = list(filter(all_hotels_location.empty, all_hotels_location))
#labeledLatLngs=all_hotels_location['labeledLatLngs']
#labeledLatLngs.head()

#for ind in range(500):
for ind in all_hotels_location.index:
    
    location = all_hotels_location['location'][ind]
    try:
        if location:
            coord=pd.DataFrame(location['labeledLatLngs'])
    except KeyError:
        print(location)
    except TypeError:
        print(location)

In [ ]:
all_hotels_location=pd.DataFrame(all_hotels[['location']]).reset_index()
pd.DataFrame(all_hotels_location['location'])['location']
#all_hotels_location['location'][0]['labeledLatLngs']

In [ ]:
all_hotels_sorted.to_csv('hotels_Resort.csv',index=False)
upload_file_cos(credentials,'hotels_Resort.csv','hotels_Resort.csv')

In [ ]:
#for ind in range(100):
#    print(all_hotels['name'][ind])

In [27]:
all_hotels = pd.read_csv('hotels_all.csv', sep=',', encoding='utf_8', index_col=False).reset_index()[['id', 'location', 'name', 'food.count', 'nightlife.count']]
all_hotels.head()

,id,location,name,food.count,nightlife.count
0,4f7350c2e4b0257534d4008b,"{'address': 'Algarve', 'lat': 37.10418, 'lng':...",402,9,2
1,575882b6498e96a54155636e,"{'lat': 37.093356, 'lng': -8.743884, 'labeledL...",A Cabana B&B,10,2
2,4e405968d164b52911d20e72,"{'lat': 37.01925600167136, 'lng': -7.933284653...",Adelaide,50,50
3,4c83a5c1d4e23704a7677288,"{'address': 'Estr. da Praia de Odeceixe', 'lat...",Agapito Odeceixe,6,0
4,4e443c15091a286cc7f80f0f,"{'address': 'Urbanização Alagoa Praia Norte, 1...",Alagoa Praia Norte,50,9

In [18]:
all_hotels.shape

(779, 3)

In [29]:
all_hotels_sorted = all_hotels.sort_values(by=['name'], ignore_index=True).reset_index()[['id', 'location', 'name', 'food.count', 'nightlife.count']]
all_hotels_sorted.drop_duplicates(subset=['id'],ignore_index=True,inplace=True)
all_hotels_sorted.head()

,id,location,name,food.count,nightlife.count
0,4f7350c2e4b0257534d4008b,"{'address': 'Algarve', 'lat': 37.10418, 'lng':...",402,9,2
1,575882b6498e96a54155636e,"{'lat': 37.093356, 'lng': -8.743884, 'labeledL...",A Cabana B&B,10,2
2,4e405968d164b52911d20e72,"{'lat': 37.01925600167136, 'lng': -7.933284653...",Adelaide,50,50
3,4c83a5c1d4e23704a7677288,"{'address': 'Estr. da Praia de Odeceixe', 'lat...",Agapito Odeceixe,6,0
4,4e443c15091a286cc7f80f0f,"{'address': 'Urbanização Alagoa Praia Norte, 1...",Alagoa Praia Norte,50,9

In [20]:
all_hotels_sorted.shape

(779, 3)

In [21]:
all_hotels_sorted[all_hotels_sorted['name'].str.contains('Aldeia')]

,id,location,name
11,4d8d5cf1cb9b224b77cc6b41,"{'lat': 37.09542707389335, 'lng': -8.170698026...",Aldeia Das Açoteias
12,5b5f54417dc9e1002c410b6a,"{'lat': 37.109169, 'lng': -8.455256, 'labeledL...",Aldeia Do Poeta
13,501d56ebe4b02330f624fd36,"{'address': 'Estrada dos Salgados', 'lat': 37....",Aldeia da Galé
14,4db9ad184df0ded98bd795ef,"{'address': 'Rua de Baixo - Casa da Pedralva',...",Aldeia da Pedralva
133,5b2594fb4a7aae002c424979,"{'address': 'Sítio da Aldeia 990Z, Santa Bárba...",Casa Da Aldeia

In [ ]:
# create map using latitude and longitude values
#37.161371, -8.166870

map_Algarve = folium.Map(location=[37.161371, -8.166870], zoom_start=10)

for ind in all_hotels_sorted.index:
    venue=all_hotels_sorted['name'][ind]
    
    location = all_hotels_sorted['location'][ind]
    try:
        coord=pd.DataFrame(location['labeledLatLngs'])
        latitude = coord['lat'][0]
        longitude = coord['lng'][0]
    except KeyError:
        latitude = location['lat']
        longitude = location['lng']

    name = u'Hotel: {}'.format(venue)
    label_html = folium.Html('<b>Hotel: Aldeia da Galé</b>', script=True)

#    if name.__contains__('Aldeia'):
        #print(name)
    #label = folium.Popup(name,parse_html=True, max_width='100%')
    label = folium.Popup(label_html,parse_html=True,max_width=2650)
    folium.CircleMarker(
        [latitude, longitude],
        radius=3,
        popup=label,
        color='blue',
        fill=True,
        #fill_color='#3186cc',
        fillOpacity=0.7).add_to(map_Algarve)

map_Algarve

In [ ]:
a=u' Aldeia Das Açoteias Aldeia da Galé'
name = u'Hotel: {}'.format(a)
label = folium.Popup(name,parse_html=True)
print(name)

In [ ]:
all_hotels_sorted['location']

In [ ]:
pd.DataFrame(all_hotels_sorted['location']).to_json()

In [ ]:
import json

In [ ]:
aaa=json.loads(all_hotels_sorted[all_hotels_sorted['name']=='452']['location'][0])
aaa

In [ ]:
all_hotels_sorted[all_hotels_sorted['name']=='452']['location'][2]

In [ ]:
all_hotels_sorted[all_hotels_sorted['name']=='452']['location'][3]

In [ ]:
category='4d4b7105d754a06374d81259' # Food
all_food=pd.DataFrame()

for ind in all_hotels_sorted.index:

    location = all_hotels_sorted['location'][ind]
    location_json = ast.literal_eval(location)
    try:
        coord=pd.DataFrame(location_json['labeledLatLngs'])
        latitude = coord['lat'][0]
        longitude = coord['lng'][0]
    except KeyError:
        latitude = location_json['lat']
        longitude = location_json['lng']

    try:
        url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}&intent=browse&categoryId={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET,
            VERSION,
            latitude,
            longitude,
            999,
            50,
            category)
        results = json_normalize(requests.get(url).json())

        if not results.empty:
            response_venues=results['response.venues'][0]
            if response_venues:
                if all_food.empty:
                    all_food=pd.DataFrame(response_venues)
                    all_hotels_sorted['food.count'] = 0
                else:
                    all_food=all_food.append(response_venues,sort=False)
                all_hotels_sorted.loc[ind, 'food.count'] = len(response_venues)

    except KeyError:
        print('Error')

print(len(all_food))

In [ ]:
all_food_sorted=all_food.sort_values(by=['name'],ignore_index=True).reset_index()[['id','location','name']]
all_food_sorted.drop_duplicates(subset=['id'],ignore_index=True,inplace=True)
all_food_sorted.head()

In [ ]:
all_food_sorted.shape

In [ ]:
all_food_sorted.to_csv('food_Hotels.csv',index=False)
upload_file_cos(credentials,'food_Hotels.csv','food_Hotels.csv')

In [ ]:
all_hotels_sorted.head()

In [ ]:
all_food_sorted.to_csv('food_Resort.csv',index=False)
upload_file_cos(credentials,'food_Resort.csv','food_Resort.csv')

In [ ]:
category = '4d4b7105d754a06376d81259'  # Nightlife Spot
all_nightlife = pd.DataFrame()

for ind in all_hotels_sorted.index:

    location = all_hotels_sorted['location'][ind]
    location_json = ast.literal_eval(location)
    try:
        coord = pd.DataFrame(location_json['labeledLatLngs'])
        latitude = coord['lat'][0]
        longitude = coord['lng'][0]
    except KeyError:
        latitude = location_json['lat']
        longitude = location_json['lng']

    try:
        url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}&intent=browse&categoryId={}'.format(
            CLIENT_ID,
            CLIENT_SECRET,
            VERSION,
            latitude,
            longitude,
            999,
            50,
            category)
        results = json_normalize(requests.get(url).json())

        if not results.empty:
            response_venues = results['response.venues'][0]
            if response_venues:
                if all_nightlife.empty:
                    all_nightlife = pd.DataFrame(response_venues)
                    all_hotels_sorted['nightlife.count'] = 0
                else:
                    all_nightlife = all_nightlife.append(response_venues, sort=False)
                all_hotels_sorted.loc[ind, 'nightlife.count'] = len(response_venues)

    except KeyError:
        print('Error')

print(len(all_nightlife))

In [ ]:
all_nightlife_sorted=all_nightlife.sort_values(by=['name'],ignore_index=True).reset_index()[['id','location','name']]
all_nightlife_sorted.drop_duplicates(subset=['id'],ignore_index=True,inplace=True)
all_nightlife_sorted.head()

In [ ]:
all_nightlife_sorted.shape

In [ ]:
all_nightlife_sorted.to_csv('nightlife_Hotels.csv',index=False)
upload_file_cos(credentials,'nightlife_Hotels.csv','nightlife_Hotels.csv')

In [23]:
all_hotels_sorted.head()

,id,location,name,latitude,longitude
0,4f7350c2e4b0257534d4008b,"{'address': 'Algarve', 'lat': 37.10418, 'lng':...",402,37.104180,-8.116300
1,575882b6498e96a54155636e,"{'lat': 37.093356, 'lng': -8.743884, 'labeledL...",A Cabana B&B,37.093356,-8.743884
2,4e405968d164b52911d20e72,"{'lat': 37.01925600167136, 'lng': -7.933284653...",Adelaide,37.019256,-7.933285
3,4c83a5c1d4e23704a7677288,"{'address': 'Estr. da Praia de Odeceixe', 'lat...",Agapito Odeceixe,37.440669,-8.798129
4,4e443c15091a286cc7f80f0f,"{'address': 'Urbanização Alagoa Praia Norte, 1...",Alagoa Praia Norte,37.177403,-7.498685

In [ ]:
all_hotels_sorted.to_csv('hotels_all.csv',index=False)
upload_file_cos(credentials,'hotels_all.csv','hotels_all.csv')

In [30]:
all_hotels_sorted['food.ratio'] = all_hotels_sorted['food.count'] / 50
all_hotels_sorted['nightlife.ratio'] = all_hotels_sorted['nightlife.count'] / 50
all_hotels_sorted.head()

,id,location,name,food.count,nightlife.count,food.ratio,nightlife.ratio
0,4f7350c2e4b0257534d4008b,"{'address': 'Algarve', 'lat': 37.10418, 'lng':...",402,9,2,0.18,0.04
1,575882b6498e96a54155636e,"{'lat': 37.093356, 'lng': -8.743884, 'labeledL...",A Cabana B&B,10,2,0.20,0.04
2,4e405968d164b52911d20e72,"{'lat': 37.01925600167136, 'lng': -7.933284653...",Adelaide,50,50,1.00,1.00
3,4c83a5c1d4e23704a7677288,"{'address': 'Estr. da Praia de Odeceixe', 'lat...",Agapito Odeceixe,6,0,0.12,0.00
4,4e443c15091a286cc7f80f0f,"{'address': 'Urbanização Alagoa Praia Norte, 1...",Alagoa Praia Norte,50,9,1.00,0.18

In [31]:
all_hotels2show_map = pd.DataFrame(all_hotels_sorted)  # .reset_index()[['id', 'name', 'food.ratio', 'nightlife.ratio']]
# all_hotels2show_map = all_hotels_sorted.reset_index()[['id', 'name', 'food.ratio', 'nightlife.ratio']]
for ind in all_hotels_sorted.index:
    location = all_hotels_sorted['location'][ind]
    location_json = ast.literal_eval(location)
    try:
        coord = pd.DataFrame(location_json['labeledLatLngs'])
        latitude = coord['lat'][0]
        longitude = coord['lng'][0]
    except KeyError:
        latitude = location_json['lat']
        longitude = location_json['lng']

    all_hotels2show_map.loc[ind, 'latitude'] = latitude
    all_hotels2show_map.loc[ind, 'longitude'] = longitude
    # all_hotels2show_map[ind, 'food.ratio'] = all_hotels_sorted['food.ratio'][ind]
    # all_hotels2show_map[ind, 'nightlife.ratio'] = all_hotels_sorted['nightlife.ratio'][ind]

# print(all_hotels2show_map.shape)
all_hotels2show_map_food_ratio = all_hotels2show_map[['latitude', 'longitude', 'food.ratio']]
all_hotels2show_map_nightlife_ratio = all_hotels2show_map[['latitude', 'longitude', 'nightlife.ratio']]

In [36]:
from folium.plugins import HeatMap

In [43]:
map_Algarve = folium.Map(location=[37.161371, -8.166870], zoom_start=10)
HeatMap(all_hotels2show_map_food_ratio).add_to(map_Algarve)
#HeatMap(all_hotels2show_map_nightlife_ratio).add_to(map_Algarve)
map_Algarve

In [44]:
map_Algarve = folium.Map(location=[37.161371, -8.166870], zoom_start=10)
#HeatMap(all_hotels2show_map_food_ratio).add_to(map_Algarve)
HeatMap(all_hotels2show_map_nightlife_ratio).add_to(map_Algarve)
map_Algarve

In [41]:
# create map using latitude and longitude values
#37.161371, -8.166870

map_Algarve = folium.Map(location=[37.161371, -8.166870], zoom_start=10)

for ind in all_hotels_sorted.index:
    venue=all_hotels_sorted['name'][ind]
    
    location = all_hotels_sorted['location'][ind]
    location_json = ast.literal_eval(location)
    try:
        coord=pd.DataFrame(location_json['labeledLatLngs'])
        latitude = coord['lat'][0]
        longitude = coord['lng'][0]
    except KeyError:
        latitude = location['lat']
        longitude = location['lng']

    label = u'Hotel: {}'.format(venue)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [latitude, longitude],
        radius=4,
        popup=label,
        color='blue',
        fill=True,
        #fill_color='#3186cc',
        fillOpacity=0.7).add_to(map_Algarve)

for ind in all_food_sorted.index:
    venue=all_food_sorted['name'][ind]
    
    location = all_food_sorted['location'][ind]
    location_json = ast.literal_eval(location)
    try:
        coord=pd.DataFrame(location_json['labeledLatLngs'])
        latitude = coord['lat'][0]
        longitude = coord['lng'][0]
    except KeyError:
        latitude = location['lat']
        longitude = location['lng']

    label = u'Food: {}'.format(venue)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [latitude, longitude],
        radius=3,
        popup=label,
        color='orange',
        fill=True,
        #fill_color='#3186cc',
        fillOpacity=0.7).add_to(map_Algarve)

map_Algarve

TypeError: string indices must be integers

In [ ]:
Resort +
4bf58dd8d48988d12f951735

Vacation Rental - apartamentos
56aa371be4b08b9a8d5734e1

Hotel Pool - just pool
4bf58dd8d48988d132951735

Bed & Breakfast - pensao
4bf58dd8d48988d1f8931735

Boarding House
4f4530a74b9074f6e4fb0100

Inn - not found
5bae9231bedf3950379f89cb

Hostel -
4bf58dd8d48988d1ee931735

Motel - apartamentos
4bf58dd8d48988d1fb931735

Nightlife Spot
4d4b7105d754a06376d81259

In [ ]:
category='4bf58dd8d48988d12f951735' # Resort
#category='4bf58dd8d48988d1fa931735' # Hotel
#category='5bae9231bedf3950379f89cb' # Inn
#category='4f4530a74b9074f6e4fb0100' # Boarding House

latitude=37.089072
longitude=-8.247880
url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}&intent=browse&categoryId={}'.format(
#url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
CLIENT_ID, 
CLIENT_SECRET,
VERSION,
latitude,
longitude,
7500,
50,
category)
results = json_normalize(requests.get(url).json())
print('Done')

In [ ]:
results.head()

In [ ]:
aa=pd.DataFrame(results['response.venues'][0])
aa.head()
#bb=pd.DataFrame(aa['location'])
#bb

In [ ]:
for ind in bb.index:
    zz = bb['location'][ind]
    xx=pd.DataFrame(zz['labeledLatLngs'])
    print(xx['lat'][0],xx['lng'][0])

In [ ]:
category='4d4b7105d754a06374d81259' # Food
#category='52e81612bcbc57f1066b7a01' # Austrian Restaurant

#37.145662, -8.124255 Algarve
#38.723653, -9.137163 Lisbon
#47.072581, 15.440042 Graz
#50.451301, 30.515182 Kiev

latitude='37.175098'
longitude='-7.38302'
url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}&intent=browse&categoryId={}'.format(
#url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
CLIENT_ID, 
CLIENT_SECRET,
VERSION,
latitude,
longitude,
500,
50,
category)
results = json_normalize(requests.get(url).json())
print('Done')

In [ ]:
results.head()

In [ ]:
aa=pd.DataFrame(results['response.venues'][0])
aa.head()

In [ ]:
latitude=37.089072
longitude=-8.247880
url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}&intent=browse&categoryId=4bf58dd8d48988d1fa931735'.format(
#url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
CLIENT_ID, 
CLIENT_SECRET,
VERSION,
latitude,
longitude,
999,
9)
results = json_normalize(requests.get(url).json())
print(results)
try:
    if not results.empty:
        response_groups=results['response.groups'][0]
        #print(type(response_groups))
        print('response_groups')
        print(response_groups)
        if response_groups:
            items=pd.DataFrame(response_groups)['items'][0]
            #print(type(items))
            print('items')
            print(items)
            if items:
                venue=pd.DataFrame(items)['venue'][0]
                #print(type(venue))
                print('venue')
                print(venue)
                if venue:
                    nearby_venues=pd.DataFrame.from_dict(venue,orient='index').T
                    #print(type(nearby_venues))
                    print('nearby_venues')
                    print(nearby_venues)

except KeyError:
    print('error')

#b=results['response.groups'][0]
#c=pd.DataFrame((b))
#d=c['items'][0]
#e=pd.DataFrame(d)['venue'][0]
#name=e['name']
#print(name)
#latitude=e['location']['lat']
#print(latitude)

In [ ]:
print(type(results))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(name))

In [ ]:
nearby_venues=pd.DataFrame(pd.DataFrame(((results)['response.groups'][0]))['items'][0])['venue'][0]
a=pd.DataFrame.from_dict(nearby_venues,orient='index').T
#a=pd.DataFrame.from_dict(nearby_venues,columns=['name','location'],orient='index')
#nearby_venues=pd.DataFrame.from_dict(pd.DataFrame(pd.DataFrame(((results)['response.groups'][0]))['items'][0])['venue'][0].items()).T
a

In [ ]:
items=pd.DataFrame(pd.DataFrame((results['response.groups'][0]))['items'][0])
items['venue'][0]

In [ ]:
venue=pd.DataFrame(pd.DataFrame(((results)['response.groups'][0]))['items'][0])['venue'][0]
name=venue['name']
print(name)
latitude=venue['location']['lat']
print(latitude)

In [ ]:
all_results=pd.DataFrame()
latitude_sum=0
longitude_sum=0
for ind in all_locations.index:
#for ind in new_df.index:

#    print(ind)
    latitude = all_locations['geometry.location.lat'][ind]
    longitude = all_locations['geometry.location.lng'][ind]
#    print(latitude)
#    print(longitude)
    latitude_sum=latitude_sum+latitude
    longitude_sum=longitude_sum+longitude
    
    url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET,
    VERSION,
    latitude,
    longitude,
    999,
    5)
#    print(url)

    results = json_normalize(requests.get(url).json())
    print(type(results))
    print('results')
#    id not results.empty and not results['response.groups'][0] and not pd.DataFrame(pd.DataFrame(results['response.groups'][0])['items'][0]).empty and not 
    try:
        if not results.empty:
            response_groups=results['response.groups'][0]
            #print(type(response_groups))
            print('response_groups')
            if response_groups:
                items=pd.DataFrame(response_groups)['items'][0]
                #print(type(items))
                print('items')
                if items:
                    venue=pd.DataFrame(items)['venue'][0]
                    #print(type(venue))
                    print('venue')
                    if venue:
                        nearby_venues=pd.DataFrame.from_dict(venue,orient='index').T
                        #print(type(nearby_venues))
                        print('nearby_venues')
                        print(nearby_venues)
                        if not nearby_venues.empty:
                            if all_results.empty:
                                all_results=pd.DataFrame(nearby_venues)
                            else:
                                all_results=all_results.append(nearby_venues,sort=False)


    except KeyError:
        print('error')

print(len(all_results))
print(latitude_sum)
print(longitude_sum)
print(latitude_sum/len(all_locations))
print(longitude_sum/len(all_locations))

In [ ]:
all_results.head()

In [ ]:
# create map using latitude and longitude values
map_Algarve = folium.Map(location=[latitude_sum/len(all_locations), longitude_sum/len(all_locations)], zoom_start=10)

for lat, lng, venue in zip(all_results['venue.location.lat'],
                                           all_results['venue.location.lng'],
                                           all_results['venue.name']):
    label = 'Venue: {}'.format(venue)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7).add_to(map_Algarve)  
    
map_Algarve

In [ ]:
all_venues=pd.DataFrame()

In [ ]:
for i in range(len(all_results)):
#    print(i)
    venues=all_results[i]['response']['groups'][0]['items']
    nearby_venues = json_normalize(venues)
    all_venues.append(nearby_venues)

print(all_venues.size)

In [ ]:
venues=all_results[0]
#venues=all_results[2]['response']['groups'][0]['items']
#print(type(all_results[15]))
#print(type(all_results[15]['response']))
#print(type(all_results[15]['response']['groups']))
#print(type(all_results[15]['response']['groups'][0]))
#print(type(venues))
nearby_venues = json_normalize(venues)
#((nearby_venues))
#nearby_venues
all_venues.append(nearby_venues)
all_venues
#print(all_venues.size)

In [ ]:
a=all_results[0].get('response')
a.get('groups')

In [ ]:
# Convert the HTML response into a BeautifulSoup Object
soup = BeautifulSoup(all_results[9].content, 'html.parser')

# Use the BeautifulSoup find_all method to extract each top site venue details.
top_venues = soup.find_all('div', class_='venueDetails')

In [ ]:
dir(all_results[9])

In [ ]:
address = 'Lagos (Algarve), Portugal'
geolocator = Nominatim()
location = geolocator.geocode(address)
print((location))
latitude = location.latitude
longitude = location.longitude

print(latitude)
print(longitude)

In [ ]:
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET,
    VERSION,
    latitude,
    longitude,
    1000,
    100)
url

In [ ]:
results = requests.get(url).json()

In [ ]:
dir(results)

In [ ]:
results.items()

In [ ]:
# Convert the HTML response into a BeautifulSoup Object
soup = BeautifulSoup(results.content, 'html.parser')

# Use the BeautifulSoup find_all method to extract each top site venue details.
top_venues = soup.find_all('div', class_='venueDetails')